name: Terrafrom Example Checks
on:
  pull_request_review:
    types: [edited, submitted]
    paths:
      - alicloud/*.go

jobs:
  ExampleCheckTest:
    if: github.event.review.state == 'approved' || github.event.review.body == 'approved'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.18.x'
      - uses: ReeganExE/github-action-job-id@v1.0
        with:
          expose-name: true
      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          # Can be "open", "closed", or "all".  Defaults to "open".
          state: open
      - uses: actions/checkout@v3
        with:
          # Checkout as many commits as needed for the diff
          fetch-depth: 2
      - name: Example Check
        run: |
          changeFiles=$(git diff --name-only HEAD^ HEAD | grep "^alicloud/" | grep ".go$" | grep -v "_test.go$" | grep -v ".markdown$")
          docsFiles=$(git diff --name-only HEAD^ HEAD | grep ".markdown$")
          diffFiles=(${docsFiles[@]} ${changeFiles[@]})
          noNeedRun=true
          exampleCount=0
          if [[ ${#diffFiles[@]} -eq 0 ]]; then
            echo -e "\033[33m[WARNING]\033[0m the pr ${prNum} does not change provider code and there is no need to check."
          #  exit 0
          fi
          for fileName in ${diffFiles[@]}; do
            if [[ ${fileName} == "alicloud/resource_alicloud"* || ${fileName} == "alicloud/data_source_alicloud"* || ${fileName} == "website/docs/r/"* ]]; then
              if [[ ${fileName} == *".go" ]]; then
                fileName=(${fileName/.go/.html.markdown})
                fileName=(${fileName#*resource_alicloud_})
              fi
              if [[ ${fileName} == *?.html.markdown ]]; then
                fileName=(${fileName#*r/})
              fi
              noNeedRun=false
              if [[ $(grep -c '```terraform' "website/docs/r/${fileName}") -lt 1 ]]; then
                echo -e "\033[33m[WARNING]\033[0m missing the acceptance test cases in the file $fileName, continue..."
                continue
              fi
              diffExampleCount=$(grep -c '```terraform' "website/docs/r/${fileName}")
              echo -e "found the example count:\n${diffExampleCount}"
              exampleCount=$(( $exampleCount + $diffExampleCount ))
            fi
          done

          if [[ "${noNeedRun}" = "false" && ${exampleCount} == "0" ]]; then
            echo -e "\033[31mthe pr ${prNum} missing docs example, please adding them. \033[0m"
            exit 1
          fi
          if [[ "${noNeedRun}" = "true" ]]; then
            echo -e "\n\033[33m[WARNING]\033[0m the pr is no need to run example.\033[0m"
            exit 0
          fi
          IN=$GH_JOB_IntegrationTest_HTML_URL
          arrIN=(${IN//actions/ })
          ossObjectPath="github-actions"${arrIN[1]}
          go run scripts/example_check.go ${ossObjectPath}
